#!/bin/bash

echo -n "To: "
read TO

echo "Type your message and please type Ctrl+D."
MSG=`cat -`

echo $MSG | openssl rsautl -encrypt -pubin -inkey ~/.ssh/other/$TO.pub > /tmp/rsa_tmp

echo `base64 </tmp/rsa_tmp | tr -d "\n"`

